/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

  0%|          | 0/113 [00:00<?, ?it/s]  0%|          | 0/113 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "./vaihingen_test.py", line 135, in <module>
    main()
  File "./vaihingen_test.py", line 112, in main
    raw_predictions = nn.Softmax(dim=1)(raw_predictions)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1376, in forward
    return F.softmax(input, self.dim, _stacklevel=5)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/nn/functional.py", line 1834, in softmax
    ret = input.softmax(dim)
AttributeError: 'NoneType' object has no attribute 'softmax'
/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

  0%|          | 0/113 [00:00<?, ?it/s]  0%|          | 0/113 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "./vaihingen_test.py", line 135, in <module>
    main()
  File "./vaihingen_test.py", line 107, in main
    raw_predictions = model(img)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/wrappers.py", line 42, in forward
    deaugmented_output = transformer.deaugment_mask(augmented_output)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/base.py", line 79, in deaugment_mask
    return self.mask_pipeline(mask)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/base.py", line 58, in __call__
    x = f(x)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/transforms.py", line 49, in apply_deaug_mask
    mask = F.vflip(mask)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/functional.py", line 17, in vflip
    return x.flip(2)
AttributeError: 'NoneType' object has no attribute 'flip'
/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

  0%|          | 0/113 [00:00<?, ?it/s]  0%|          | 0/113 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "./vaihingen_test.py", line 135, in <module>
    main()
  File "./vaihingen_test.py", line 107, in main
    raw_predictions = model(img)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/wrappers.py", line 42, in forward
    deaugmented_output = transformer.deaugment_mask(augmented_output)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/base.py", line 79, in deaugment_mask
    return self.mask_pipeline(mask)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/base.py", line 58, in __call__
    x = f(x)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/transforms.py", line 128, in apply_deaug_mask
    mask = F.scale(
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/ttach/functional.py", line 47, in scale
    h, w = x.shape[2:]
AttributeError: 'NoneType' object has no attribute 'shape'
/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning:

Checkpoint directory /disk1/lhl/workspace/unetformer/GeoSeg/model_weights/vaihingen/unetformer-cascadvote-r18-512-crop-ms-e100 exists and is not empty.

/disk1/lhl/workspace/unetformer/GeoSeg/tools/metric.py:30: RuntimeWarning:

invalid value encountered in divide

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:432: UserWarning:

The number of training samples (46) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/workspace/unetformer/GeoSeg/tools/metric.py:30: RuntimeWarning:

invalid value encountered in divide

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:432: UserWarning:

The number of training samples (46) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Traceback (most recent call last):
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/resource_sharer.py", line 149, in _serve
    send(conn, destination_pid)
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/resource_sharer.py", line 50, in send
    reduction.send_handle(conn, new_fd, pid)
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/reduction.py", line 184, in send_handle
    sendfds(s, [handle])
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/reduction.py", line 149, in sendfds
    sock.sendmsg([msg], [(socket.SOL_SOCKET, socket.SCM_RIGHTS, fds)])
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/resource_sharer.py", line 151, in _serve
    close()
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/resource_sharer.py", line 52, in close
    os.close(new_fd)
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "./train_supervision_vote.py", line 274, in <module>
    main()
  File "./train_supervision_vote.py", line 248, in main
    trainer.fit(model=model)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 146, in run
    self.on_advance_end()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 242, in on_advance_end
    self._run_validation()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 337, in _run_validation
    self.val_loop.run()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 104, in advance
    batch_idx, (batch, self.batch_progress.is_last_batch) = next(self._dataloader_iter)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 203, in __next__
    return self.fetching_function()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 270, in fetching_function
    self._fetch_next_batch()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 300, in _fetch_next_batch
    batch = next(self.dataloader_iter)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1325, in _get_data
    success, data = self._try_get_data()
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 297, in rebuild_storage_fd
    fd = df.detach()
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/disk1/lhl/env/airs/lib/python3.8/multiprocessing/reduction.py", line 159, in recvfds
    raise EOFError
EOFError
/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning:

Checkpoint directory /disk1/lhl/workspace/unetformer/GeoSeg/model_weights/vaihingen/unetformer-cascadvote-r18-512-crop-ms-e100 exists and is not empty.

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning:

The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

/disk1/lhl/workspace/unetformer/GeoSeg/tools/metric.py:29: RuntimeWarning:

invalid value encountered in divide

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning:

The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:432: UserWarning:

The number of training samples (46) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Killed
/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning:

Checkpoint directory /disk1/lhl/workspace/unetformer/GeoSeg/model_weights/vaihingen/unetformer-cascadvote-r18-512-crop-ms-e100 exists and is not empty.

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning:

The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

/disk1/lhl/workspace/unetformer/GeoSeg/tools/metric.py:30: RuntimeWarning:

invalid value encountered in divide

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning:

The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:432: UserWarning:

The number of training samples (46) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning:

Checkpoint directory /disk1/lhl/workspace/unetformer/GeoSeg/model_weights/vaihingen/unetformer-cascadvote-r18-512-crop-ms-e100 exists and is not empty.

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning:

The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

/disk1/lhl/workspace/unetformer/GeoSeg/tools/metric.py:29: RuntimeWarning:

invalid value encountered in divide

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning:

The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:432: UserWarning:

The number of training samples (46) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning:

Checkpoint directory /disk1/lhl/workspace/unetformer/GeoSeg/model_weights/vaihingen/unetformer-cascadvote-r18-512-crop-ms-e100 exists and is not empty.

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning:

The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning:

The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

/disk1/lhl/env/airs/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:432: UserWarning:

The number of training samples (46) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

/disk1/lhl/workspace/unetformer/GeoSeg/tools/metric.py:29: RuntimeWarning:

invalid value encountered in divide

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name | Type                  | Params
-----------------------------------------------
0 | net  | UNetFormerVote        | 12.0 M
1 | loss | VoteStageTrainingLoss | 0     
-----------------------------------------------
12.0 M    Trainable params
0         Non-trainable params
12.0 M    Total params
47.882    Total estimated model params size (MB)
/disk1/lhl/env/airs/lib/python3.8/site-packages/torch/functional.py:478: UserWarning:

torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/aten/src/ATen/native/TensorShape.cpp:2895.)

test_out_vote/main/ 创建成功
test_out_vote/head_1/ 创建成功
test_out_vote/head_2/ 创建成功
test_out_vote/confid_vote/ 创建成功
test_out_vote/prob_vote/ 创建成功
Traceback (most recent call last):
  File "./vaihingen_test_cascadvote.py", line 268, in <module>
    main()
  File "./vaihingen_test_cascadvote.py", line 121, in main
    evaluator = Evaluatorv2(num_class=config.num_classes,out_folder='{}/confid_vote/'.format(args.output_path))
NameError: name 'Evaluatorv2' is not defined
